### ISSUE TITLE
False `group.probs must sum to 1` error

### ISSUE THREAD

**Issue by scottgigante** [Oshlack/splatter#74]
I'm getting this error even though I'm pretty sure my group probs sum to 1 (unless I missed something in grade 3 fractions class!)
```
> splatSimulate(group.prob=c(0.3, 0.3, 0.3, 0.1))
Getting parameters...
Error in validObject(object) :
  invalid class “SplatParams” object: : group.probs must sum to 1
> splatter:::.__NAMESPACE__.$spec
      name    version
"splatter"    "1.6.1"
```

**Comment by lazappi** [comment]
I've just tried this on the latest release and devel versions without any problems. It's possible I fixed it in some of the recent updates. Could you try using the release version (v1.8.0)?

**Comment by scottgigante** [comment]
Maybe I'm doing something wrong here - 1.6.1 is what installs for me using `BiocManager::install("splatter")`. Running R 3.5.1.

**Comment by lazappi** [comment]
Ah, the latest release of Bioconductor requires R 3.6 so that will be why it won't install a later version. I think the best option is probably to install it from GitHub using `remotes::install_github("Oshlack/splatter@RELEASE_3_9")`. That should install Splatter v1.8.0. There shouldn't be anything that needs R 3.6 in Splatter itself.

**Comment by lazappi** [comment]
Did you manage to sort this out? Just check before I close the issue.

**Comment by scottgigante** [comment]
I haven't, but purely because I changed my work flow and am able to avoid
the issue. When I eventually get around to updating, I'll reopen if it's
still a problem.
